# Generated by Django 4.2.6 on 2023-10-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
                ('data', models.DateField()),
            ],
        ),
    ]
